from ast import Lambda
from tkinter import *

r=Tk()
t=Entry(r,width=48,borderwidth=5)
t.grid(row=0,column=0,columnspan=4,padx=30,pady=15)
r.title("Calculator")
def button_add(number):
#  t.insert(0,number)
 return
button_1=Button(r,text="1",padx=40,pady=20,command=button_add)
button_2=Button(r,text="2",padx=40,pady=20,command= button_add)
button_3=Button(r,text="3",padx=40,pady=20,command=button_add)
button_4=Button(r,text="4",padx=40,pady=20,command=button_add)
button_5=Button(r,text="5",padx=40,pady=20,command=button_add)
button_6=Button(r,text="6",padx=40,pady=20,command=button_add)
button_7=Button(r,text="7",padx=40,pady=20,command=button_add)
button_8=Button(r,text="8",padx=40,pady=20,command=button_add)
button_9=Button(r,text="9",padx=40,pady=20,command=button_add)
button_10=Button(r,text="C",padx=40,pady=20,command=button_add)
button_11=Button(r,text="_/",padx=38,pady=20,command=button_add)
button_12=Button(r,text="^",padx=39,pady=20,command=button_add) 
button_13=Button(r,text="%",padx=40,pady=20,command=button_add)
button_14=Button(r,text="+",padx=40,pady=20,command=button_add)
button_15=Button(r,text="-",padx=40,pady=20,command=button_add)
button_16=Button(r,text="*",padx=40,pady=20,command=button_add)
button_17=Button(r,text="/",padx=40,pady=20,command=button_add)
button_18=Button(r,text="=",padx=40,pady=20,command=button_add,bg="orange")
button_19=Button(r,text=".",padx=41,pady=20,command=button_add)
button_0=Button(r,text="0",padx=40,pady=20,command=button_add)
button_1.grid(row=4,column=0)
button_2.grid(row=4,column=1)
button_3.grid(row=4,column=2)
button_4.grid(row=3,column=0)
button_5.grid(row=3,column=1)
button_6.grid(row=3,column=2)
button_7.grid(row=2,column=0)
button_8.grid(row=2,column=1)
button_9.grid(row=2,column=2)
button_10.grid(row=1,column=0)
button_11.grid(row=1,column=1)
button_12.grid(row=1,column=2)
button_13.grid(row=1,column=3)
button_14.grid(row=2,column=3)
button_15.grid(row=3,column=3)
button_16.grid(row=4,column=3)
button_17.grid(row=5,column=3)
button_18.grid(row=5,column=2)
button_19.grid(row=5,column=1)
button_0.grid(row=5,column=0)


r.mainloop()